import React from 'react';

const TermsPage: React.FC = () => {
  return (
    <div className="prose prose-invert max-w-4xl mx-auto py-8 px-4 animate-fade-in">
      <h1>Terms of Service</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>

      <h2>1. Agreement to Terms</h2>
      <p>
        By accessing or using Sales Coach AI (the "Service"), you agree to be bound by these Terms of Service ("Terms").
        If you disagree with any part of the terms, then you may not access the Service. This is a legally binding
        agreement between you and the operators of Sales Coach AI.
      </p>

      <h2>2. The Service</h2>
      <p>
        Sales Coach AI provides users with the ability to upload audio files of sales calls to receive an AI-generated
        analysis, which includes a transcription, sentiment analysis, and coaching feedback (the "Analysis"). You
        acknowledge that the Analysis is generated by an automated system and may contain errors or inaccuracies. The
        Service is provided for informational and coaching purposes only and should not be solely relied upon for making
        critical business decisions.
      </p>

      <h2>3. User Responsibilities and Conduct</h2>
      <p>
        You are solely responsible for the audio files and any other content you upload to the Service ("User Content").
        By uploading User Content, you represent and warrant that:
      </p>
      <ul>
        <li>You have obtained all necessary rights, releases, and permissions to record, upload, and process the User Content, including the consent of all individuals recorded in the audio files.</li>
        <li>Your User Content does not and will not infringe upon or violate the rights of any third party, including intellectual property rights and rights of privacy.</li>
        <li>Your User Content does not contain any material that is unlawful, defamatory, obscene, or otherwise objectionable.</li>
      </ul>
      <p>
        You agree not to use the Service for any purpose that is illegal or prohibited by these Terms.
      </p>
      
      <h2>4. Intellectual Property</h2>
      <p>
        You retain all ownership rights to your User Content. However, by uploading User Content, you grant Sales Coach
        AI a temporary, worldwide, non-exclusive, royalty-free license to use, reproduce, and process the User Content
        solely for the purpose of providing the Service and generating the Analysis for you. This license terminates
        automatically once the Analysis has been delivered to your session.
      </p>
       <p>
        All rights, title, and interest in and to the Service itself, including its software, design, and branding, are
        and will remain the exclusive property of Sales Coach AI and its licensors.
      </p>

      <h2>5. Disclaimer of Warranties</h2>
      <p>
        The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Sales Coach AI makes no warranty, express or
        implied, that the Service or the Analysis will be accurate, reliable, secure, or error-free. You use the
        Service at your own risk. We expressly disclaim all warranties, including the implied warranties of
        merchantability, fitness for a particular purpose, and non-infringement.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        In no event shall Sales Coach AI, its directors, employees, or partners be liable for any indirect, incidental,
        special, consequential, or punitive damages, including without limitation, loss of profits, data, or goodwill,
        arising from your use of the Service or any Analysis provided.
      </p>

      <h2>7. Changes to Terms</h2>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide
        notice of any changes by posting the new Terms on this page. By continuing to access or use our Service after
        those revisions become effective, you agree to be bound by the revised terms.
      </p>

      <h2>8. Governing Law</h2>
      <p>
        These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the
        operators of Sales Coach AI reside, without regard to its conflict of law provisions.
      </p>
    </div>
  );
};

export default TermsPage;