import React from 'react';
import { FileTextIcon } from '../icons/FileTextIcon';
import { ClipboardListIcon } from '../icons/ClipboardListIcon';
import { UserCheckIcon } from '../icons/UserCheckIcon';
import { LockIcon } from '../icons/LockIcon';
import { GavelIcon } from '../icons/GavelIcon';
import { InfoIcon } from '../icons/InfoIcon';

interface Section {
  id: string;
  title: string;
  icon: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  summary: string;
  content: React.ReactNode;
}

const sections: Section[] = [
  {
    id: 'agreement',
    title: 'Agreement to Terms',
    icon: FileTextIcon,
    summary: 'By using this app, you agree to these rules. It’s a binding contract.',
    content: (
      <p>
        By accessing or using Clarity AI (the "Service"), you agree to be bound by these Terms of Service ("Terms").
        If you disagree with any part of the terms, then you may not access the Service. This is a legally binding
        agreement between you and the operators of Clarity AI.
      </p>
    ),
  },
  {
    id: 'service',
    title: 'The Service',
    icon: ClipboardListIcon,
    summary: 'Our AI analyzes your audio to give you feedback. This is for coaching, not critical decisions, and the AI can make mistakes.',
    content: (
      <p>
        Clarity AI provides users with the ability to upload audio files of conversations to receive an AI-generated
        analysis, which includes a transcription, sentiment analysis, and coaching feedback (the "Analysis"). You
        acknowledge that the Analysis is generated by an automated system and may contain errors or inaccuracies. The
        Service is provided for informational and coaching purposes only and should not be solely relied upon for making
        critical business or career decisions.
      </p>
    ),
  },
  {
    id: 'responsibilities',
    title: 'User Responsibilities',
    icon: UserCheckIcon,
    summary: 'You are responsible for the audio you upload. You must have permission from everyone recorded and ensure it’s not illegal or offensive.',
    content: (
      <>
        <p>
          You are solely responsible for the audio files and any other content you upload to the Service ("User Content").
          By uploading User Content, you represent and warrant that:
        </p>
        <ul className="list-disc list-inside space-y-2 mt-2">
          <li>You have obtained all necessary rights, releases, and permissions to record, upload, and process the User Content, including the consent of all individuals recorded in the audio files.</li>
          <li>Your User Content does not and will not infringe upon or violate the rights of any third party, including intellectual property rights and rights of privacy.</li>
          <li>Your User Content does not contain any material that is unlawful, defamatory, obscene, or otherwise objectionable.</li>
        </ul>
        <p className="mt-2">
          You agree not to use the Service for any purpose that is illegal or prohibited by these Terms.
        </p>
      </>
    ),
  },
  {
    id: 'ip',
    title: 'Intellectual Property',
    icon: LockIcon,
    summary: 'You own your audio. We only get a temporary license to analyze it for you, which ends after the analysis. We own our app and brand.',
    content: (
       <>
        <p>
          You retain all ownership rights to your User Content. However, by uploading User Content, you grant Clarity
          AI a temporary, worldwide, non-exclusive, royalty-free license to use, reproduce, and process the User Content
          solely for the purpose of providing the Service and generating the Analysis for you. This license terminates
          automatically once the Analysis has been delivered to your session.
        </p>
         <p className="mt-2">
          All rights, title, and interest in and to the Service itself, including its software, design, and branding, are
          and will remain the exclusive property of Clarity AI and its licensors.
        </p>
      </>
    ),
  },
  {
    id: 'disclaimer',
    title: 'Disclaimer & Liability',
    icon: InfoIcon,
    summary: 'The app is provided "as is." We don\'t guarantee it will be perfect or accurate, and we are not liable for any damages from its use.',
    content: (
        <>
        <h3 className="text-lg font-semibold text-content-100 dark:text-dark-content-100 mb-2">Disclaimer of Warranties</h3>
        <p>
          The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Clarity AI makes no warranty, express or
          implied, that the Service or the Analysis will be accurate, reliable, secure, or error-free. You use the
          Service at your own risk. We expressly disclaim all warranties, including the implied warranties of
          merchantability, fitness for a particular purpose, and non-infringement.
        </p>
         <h3 className="text-lg font-semibold text-content-100 dark:text-dark-content-100 mt-4 mb-2">Limitation of Liability</h3>
        <p>
          In no event shall Clarity AI, its directors, employees, or partners be liable for any indirect, incidental,
          special, consequential, or punitive damages, including without limitation, loss of profits, data, or goodwill,
          arising from your use of the Service or any Analysis provided.
        </p>
      </>
    ),
  },
  {
    id: 'governing-law',
    title: 'Governing Law & Changes',
    icon: GavelIcon,
    summary: 'The laws of our jurisdiction govern these terms. We can change these terms at any time and will post updates here.',
    content: (
      <>
        <h3 className="text-lg font-semibold text-content-100 dark:text-dark-content-100 mb-2">Changes to Terms</h3>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide
          notice of any changes by posting the new Terms on this page. By continuing to access or use our Service after
          those revisions become effective, you agree to be bound by the revised terms.
        </p>
        <h3 className="text-lg font-semibold text-content-100 dark:text-dark-content-100 mt-4 mb-2">Governing Law</h3>
        <p>
          These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the
          operators of Clarity AI reside, without regard to its conflict of law provisions.
        </p>
      </>
    ),
  }
];

const SectionCard: React.FC<{ section: Section }> = ({ section }) => (
  <div id={section.id} className="bg-base-200 dark:bg-dark-base-200 p-6 rounded-lg shadow-md border border-base-300 dark:border-dark-base-300">
    <div className="flex items-start gap-4">
      <section.icon className="w-8 h-8 text-brand-primary dark:text-dark-brand-primary flex-shrink-0 mt-1" />
      <div>
        <h2 className="text-xl font-bold text-content-100 dark:text-dark-content-100">{section.title}</h2>
        <p className="mt-2 text-sm italic p-3 bg-base-100 dark:bg-dark-base-100 rounded-md border-l-4 border-brand-accent dark:border-dark-brand-accent">
          <strong>In Plain English:</strong> {section.summary}
        </p>
        <div className="mt-4 text-content-200 dark:text-dark-content-200 text-sm leading-relaxed space-y-2">
          {section.content}
        </div>
      </div>
    </div>
  </div>
);

const TermsPage: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto py-8 px-4 animate-fade-in">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-extrabold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-content-200 dark:text-dark-content-200">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="flex flex-col lg:flex-row gap-12">
        {/* Main Content */}
        <div className="lg:w-2/3 space-y-8">
          {sections.map(section => (
            <SectionCard key={section.id} section={section} />
          ))}
        </div>

        {/* Sticky Navigation */}
        <aside className="lg:w-1/3">
          <div className="sticky top-24">
            <h3 className="text-lg font-semibold mb-4 border-b border-base-300 dark:border-dark-base-300 pb-2">On this page</h3>
            <ul className="space-y-2">
              {sections.map(section => (
                <li key={section.id}>
                  <a
                    href={`#${section.id}`}
                    className="flex items-center gap-3 text-sm text-content-200 dark:text-dark-content-200 hover:text-brand-primary dark:hover:text-dark-brand-primary font-medium transition-colors"
                  >
                     <section.icon className="w-4 h-4 flex-shrink-0" />
                    <span>{section.title}</span>
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  );
};

export default TermsPage;